"""create scraped_jobs and user_jobs tables

Revision ID: 003
Revises: 002
Create Date: 2026-04-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create scraped_jobs table
    op.create_table(
        'scraped_jobs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('external_url', sa.String(length=500), nullable=True),
        sa.Column('company_name', sa.String(length=255), nullable=False),
        sa.Column('job_title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('description_hash', sa.String(length=64), nullable=True),  # SHA-256 hash of first 200 chars for cross-platform deduplication
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('source_platform', sa.String(length=100), nullable=True),
        sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('external_url'),  # Prevent duplicate job URLs
        sa.UniqueConstraint(
            'company_name',
            'job_title',
            'description_hash',
            name='uq_job_dedup'  # Cross-platform deduplication constraint
        )
    )
    op.create_index(op.f('ix_scraped_jobs_description_hash'), 'scraped_jobs', ['description_hash'], unique=False)

    # Create user_jobs table (many-to-many association with AI-generated content)
    op.create_table(
        'user_jobs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('match_score', sa.SmallInteger(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='new'),
        sa.Column('optimized_cv', postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # ATS-optimized CV from CV Optimizer agent
        sa.Column('cover_letter', sa.Text(), nullable=True),  # Generated cover letter
        sa.Column('interview_prep', postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # Interview questions and cheat sheets
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('match_score BETWEEN 0 AND 100', name='ck_userjob_match_score'),
        sa.CheckConstraint(
            "status IN ('new', 'applied', 'saved', 'hidden', 'duplicate')",
            name='ck_userjob_status'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['job_id'], ['scraped_jobs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job')
    )
    op.create_index(op.f('ix_user_jobs_user_id'), 'user_jobs', ['user_id'], unique=False)

    # Composite index for dashboard queries (jobs filtered by user and status)
    op.create_index(
        'ix_user_jobs_user_status',
        'user_jobs',
        ['user_id', 'status']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_jobs_user_status', table_name='user_jobs')
    op.drop_index(op.f('ix_user_jobs_user_id'), table_name='user_jobs')
    op.drop_table('user_jobs')
    op.drop_index(op.f('ix_scraped_jobs_description_hash'), table_name='scraped_jobs')
    op.drop_table('scraped_jobs')
    # ### end Alembic commands ###
